- api/api.go
- cmd/framesd/framesd.go
- config_example.toml
- end2end_test.go
- log.go
- server/server.go
- server/server_example_test.go
- types.go
> Verbose -> Log.Level

- .gitignore
- .travis.yml
- backends/csv/backend.go
- backends/utils/utils.go
- clients/py/tests/test_integration.py
- clients/py/tests/test_v3io_frames.py
- clients/py/v3io_frames.py
- end2end_test.go
- frame.go
- labelcol.go
- labelcol_test.go
- marshal.go
- slicecol.go
- slicecol_test.go
> Bool array

- clients/py/v3io_frames.py
> Remove unique check

- backends/kv/writer.go
- v3ioutils/schema.go
> KV timeout

- clients/py/tests/test_integration.py
- clients/py/v3io_frames.py
- frameimpl.go
- marshal.go
- server/server.go
> Errors to client

- cmd/framesd/framesd.go
- server/server.go
Fixed #75. Also added a fix to `framesd` taking time to detect errors.
> Error from write

- backends/tsdb/backend.go
- http/server.go
fix TSDB access key and add access key to basic auth
> fix-tsdb-accesskey

- clients/py/v3io_frames/pbutils.py
- clients/py/v3io_frames/pdutils.py
* remove duplicate indices assignment
* add default sort to concat (avoid concat warnings)
> Dev --> Master (0.4.2)

- Jenkinsfile
* change stage order
* fix frames pypi version
> update frames pypi version

- clients/py/tests/test_pbutils.py
- clients/py/v3io_frames/pbutils.py
> IG-11266: Support writing and reading dataframes with unnamed columns.

- backends/kv/reader.go
- clients/py/v3io_frames/pbutils.py
- v3ioutils/schema.go
fixes:
- show key column - both in KV (key column) and TSDB (timstamp)
- fix naming issue of index columns
- fix empty line in KV DF - caused by bad processing of the schema file
- fix schema file being written as `.%23schema` rather than `.#schema`
> IG-11923 & IG-11924 & IG-11925 & IG-12009

- go.mod
- go.sum
E.g. when the server defines a password and the client passes an access key.
> Update v3io-go version avoid error when access key and password are both defined.

- clients/py/v3io_frames/http.py
Requires updating the python client in Jupyter.
> IG-12445: Fix chopped body error when reading from ingress.

- http/server.go
Currently, if the client defined with a target URL of `http://localhost:8080/` or similar, the client will get a MemoryError when it attempts to read. This change fixes that on the server side.
> Fix MemoryError caused by bad server response when url contains a trailing slash.

- backends/kv/writer.go
- clients/py/v3io_frames/grpc.py
- clients/py/v3io_frames/http.py
- clients/py/v3io_frames/pbutils.py
- clients/py/v3io_frames/pdutils.py
fix index name on kv write +  fix index attributes saved only as string
> IG-12825 & IG-12811

- v3ioutils/schema.go
- v3ioutils/schema_test.go
* IG-13261: Fix schema merge logic.
* Added a regression test for IG-13261.
> IG-13261: Fix schema merge logic. (#284)

- README.md
> [DOC] README: Filter out update-expression refs (not supported) [IG-12272]

- .gitignore
- api/api.go
- backends/tsdb/backend.go
- backends/tsdb/reader.go
- backends/tsdb/writer.go
- config.go
- go.mod
- go.sum
- http/server.go
Also reduce log level for per-request logs.
> Cache TSDB queriers.

- README.md
@talIguaz please review and merge.
> [DOC] Frames README: Minor doc fixes and improvements

- README.md
- clients/py/v3io_frames/client.py
@talIguaz please review and merge.
> [DOC] README & help text: `delete` doc fixes & improvements

- backends/kv/writer.go
change the error codes based on new engine codes
> change write condition error codes

- clients/py/Makefile
- clients/py/v3io_frames/pbutils.py
200k entries took 15 seconds to write before null support, 60 seconds with null support, and 24 seconds after this optimization.
> Improve performance of null handling code on write.

- go.mod
- go.sum
To get the fix for https://github.com/stretchr/testify/issues/771
> Update testify version.

- backends/tsdb/backend.go
- test/tsdb_integration_test.go
fix time parsing in tsdb delete
> IG-14093 & IG-14096

- backends/kv/writer.go
- backends/kv/writer_test.go
- go.sum
- test/csv_integration_test.go
- test/kv_integration_test.go
- test/stream_integration_test.go
- test/test_utils.go
- test/tsdb_integration_test.go
Support referring to index column in update expression + handle time types
> IG-14113 & 14112

- clients/py/Pipfile
- clients/py/Pipfile.lock
> Revert "IG-14304: Update Python dependencies and add test dependencies to Pipfile."

- backends/tsdb/reader.go
- builder.go
- frame.go
- go.mod
- go.sum
- types.go
~~~
deps:
v3io-tsdb:
git_url: git@github.com:imakhlin/v3io-tsdb.git
branch: IG-14794
~~~
> IG-14794: handle 'nil' values

- api/api.go
- backends/kv/reader.go
- go.sum
> IG-14947: handle file not found error

- api/api.go
- clients/py/v3io_frames/pdutils.py
> Fix lex column reorder on wildcard query in Python client.

- backends/kv/writer.go
- test/kv_integration_test.go
> IG-15131: error when writing 'None' value with 'updateItem' save mode

- http/grafana.go
Before this change, the response column order is nondeterministic.
After this change, response columns are in the requested order, or sorted lexicographically in case of a wildcard request.
> IG-12645: Fix grafana response column order.

- clients/py/v3io_frames/grpc.py
to avoid exceeding max message size.
> IG-13996: Split dataframe on write when using GRPC transport

- go.mod
- test/kv_integration_test.go
- recreate appender for the second phase of the test
> Fix TestUpdateExpressionWithNullValues

- framulate/framulate.go
- framulate/writeverify.go
* framulate memory
* order
Co-authored-by: Eran Duchan <erand@iguazio.com>
> Framulate: reduce memory usage + support pprof (#426)

- api/api.go
- config.go
> IG-15635: Make dial timeout configurable. Default to 10s.

- api/api.go
- config.go
- go.mod
- go.sum
Depends on https://github.com/v3io/v3io-go/pull/66
> IG-15850: Global connection semaphore. Default to unlimited max connection per host.

- clients/py/Pipfile.lock
Resolves https://github.com/v3io/frames/network/alerts.
Ran tests and manual sanity check (client.write).
> Update piplock (python dependencies).

- backends/kv/writer.go
- backends/kv/writer_test.go
Broken by #480 (fix for IG-16104).
> IG-16201: Fix empty index support.

- go.sum
Co-authored-by: Gal Topper <galt@iguazio.com>
> Fix go.sum. (#495)

- Makefile
Co-authored-by: Gal Topper <galt@iguazio.com>
> Increase linter timeout. (#500)

- clients/py/v3io_frames/client.py
- clients/py/v3io_frames/http.py
Trim down delete request over HTTP.
> IG-15373: Fix erroneous validation error on non-TSDB delete.

- backends/utils/history_server.go
the bug is basically logs being written to the wrong log file.
> IG-16340 - fix history log writing

- http/grafana.go
Co-authored-by: Dina Nimrodi <dinan@iguazio.com>
> don't pass start,end and query to kv from grafana (#531)

- clients/py/v3io_frames/pbutils.py
* add tz to empty value
* tidy
* remove cyclic dep
Co-authored-by: Dina Nimrodi <dinan@iguazio.com>
> IG-16853 - add tz to empty value (#538)

- clients/py/tests/test_integration.py
- go.sum
> fix python datetime test

- clients/py/v3io_frames/client.py
Co-authored-by: Gal Topper <galt@iguazio.com>
> IG-17893: Fix wrapping of pandas-compatible dataframes e.g. cuDF. (#589)

- clients/py/v3io_frames/__init__.py
- clients/py/v3io_frames/client.py
* IG-17893: Convert non-pandas DFs to pandas.
* Update frames client version.
* Return on dfs=None.
* Retain previous behaviour on dfs=None.
Co-authored-by: Gal Topper <galt@iguazio.com>
> IG-17893: Convert non-pandas DFs to pandas. (#593)

- clients/py/Pipfile
- clients/py/Pipfile.lock
- clients/py/docs/requirements.txt
> 0.8.x: Loosen grpcio requirements
